name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: yarn nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn playwright install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4
      - run: yarn nx affected -t lint test build e2e-ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: dist\.playwright\e2e\playwright-report
          retention-days: 30